using BlitzText.Windows.Models;

namespace BlitzText.Windows.Services;

public static class Localizer
{
    private static readonly IReadOnlyDictionary<string, string> German = new Dictionary<string, string>
    {
        ["Subtitle"] = "Diktieren, transkribieren und direkt in die richtige App einfuegen.",
        ["Controls"] = "Bedienung",
        ["DefaultMode"] = "Standardmodus fuer den Aufnahmebutton.",
        ["Workflow"] = "Workflow",
        ["Transcription"] = "Transkription",
        ["Rewrite"] = "Umschreiben",
        ["AppLanguage"] = "App-Sprache",
        ["DictationLanguage"] = "Diktatsprache",
        ["AutoPaste"] = "Nach Abschluss automatisch einfuegen",
        ["KeepOllamaWarm"] = "Ollama warmhalten",
        ["SaveHistory"] = "Verlauf speichern",
        ["Status"] = "Status",
        ["Ready"] = "Bereit",
        ["AutoSaveHint"] = "Aenderungen werden automatisch gespeichert.",
        ["AutoSaving"] = "Speichere automatisch...",
        ["AutoSaved"] = "Automatisch gespeichert",
        ["AutoSaveFailed"] = "Automatisches Speichern fehlgeschlagen",
        ["RecordButtonTip"] = "Startet oder stoppt die Aufnahme. Hotkey",
        ["Provider"] = "Provider",
        ["Hotkeys"] = "Hotkeys",
        ["Prompts"] = "Prompts",
        ["Backup"] = "Backup",
        ["Version"] = "Version",
        ["CheckUpdates"] = "Nach Updates suchen",
        ["OpenDownload"] = "Download oeffnen",
        ["UpdateNotChecked"] = "Noch nicht nach Updates gesucht.",
        ["CheckingUpdates"] = "Suche nach Updates...",
        ["AppIsCurrent"] = "BlitzText ist aktuell ({0}).",
        ["UpdateAvailable"] = "Update verfuegbar: Version {0}.",
        ["UpdateCheckFailed"] = "Update-Pruefung fehlgeschlagen: {0}",
        ["Results"] = "Ergebnis",
        ["OpenAiKeyHint"] = "Der API-Key wird im Windows Credential Manager gespeichert.",
        ["TranscriptionModel"] = "Transkriptionsmodell",
        ["RewriteModel"] = "Rewrite-Modell",
        ["OpenRouterHint"] = "Optionaler Rewrite-Provider ueber OpenRouter.",
        ["AnthropicHint"] = "Optionaler Rewrite-Provider fuer Claude-Modelle.",
        ["LocalTranscription"] = "Lokale Transkription",
        ["LocalTranscriptionHint"] = "Optional: whisper.cpp EXE und ein lokales Whisper-Modell.",
        ["WhisperModel"] = "Whisper-Modell",
        ["FoundWhisperModels"] = "Gefundene Modelle",
        ["WhisperTimeout"] = "Timeout Sekunden",
        ["TestWhisper"] = "Whisper testen",
        ["Browse"] = "...",
        ["OllamaHint"] = "Lokaler oder Netzwerk-Ollama-Server fuer Umschreiben.",
        ["TestOllama"] = "Ollama testen",
        ["Detect"] = "Erkennen",
        ["HotkeysActive"] = "Workflow-Hotkeys aktiv.",
        ["RestoreDefaultHotkeys"] = "Standard-Hotkeys wiederherstellen",
        ["CustomNames"] = "Eigennamen",
        ["CustomNamesHint"] = "Ein Name oder Begriff pro Zeile. Diese Schreibweisen werden als Kontext mitgegeben.",
        ["TranscriptionHint"] = "Transkriptionshinweis",
        ["TranscriptionHintHelp"] = "Optionaler Hinweis fuer Speech-to-Text, z. B. Sprache, Fachbegriffe oder Schreibweisen.",
        ["WorkflowPrompts"] = "Workflow-Prompts",
        ["WorkflowPromptsHint"] = "Diese Zusatzanweisungen werden beim Umschreiben an OpenAI oder Ollama gesendet.",
        ["PromptPresets"] = "Prompt-Vorlagen (Verbessern)",
        ["PromptPresetsHint"] = "Diese Vorlagen setzen den Prompt fuer den Improve-Modus (Verbessern).",
        ["Apply"] = "Anwenden",
        ["Improve"] = "Verbessern",
        ["Calm"] = "Entschaerfen",
        ["Emojis"] = "Emojis ergaenzen",
        ["TranscribeOnly"] = "Nur transkribieren",
        ["ResetPrompts"] = "Prompts zuruecksetzen",
        ["ExportSettings"] = "Einstellungen exportieren",
        ["ExportSettingsHint"] = "Speichert Provider, Hotkeys, Prompts und Workflow-Auswahl als JSON-Datei. API-Keys werden nicht exportiert.",
        ["Export"] = "Exportieren",
        ["ImportSettings"] = "Einstellungen importieren",
        ["ImportSettingsHint"] = "Uebernimmt eine zuvor exportierte JSON-Datei. Bestehende API-Schluessel bleiben lokal erhalten.",
        ["Import"] = "Importieren",
        ["Copy"] = "Kopieren",
        ["Paste"] = "Einfuegen",
        ["Delete"] = "Loeschen",
        ["SearchHistory"] = "Verlauf durchsuchen...",
        ["SearchHistoryLabel"] = "Verlauf durchsuchen",
        ["ClearHistory"] = "Verlauf leeren",
        ["Footer"] = "Hotkey druecken, sprechen, Hotkey erneut druecken. Das Ergebnis landet in der Zwischenablage oder direkt im Ziel-Fenster.",
        ["StartRecording"] = "Aufnahme starten",
        ["StopRecording"] = "Aufnahme stoppen",
        ["Cancel"] = "Abbrechen"
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["Subtitle"] = "Dictate, transcribe, and paste directly into the right app.",
        ["Controls"] = "Controls",
        ["DefaultMode"] = "Default mode for the record button.",
        ["Workflow"] = "Workflow",
        ["Transcription"] = "Transcription",
        ["Rewrite"] = "Rewrite",
        ["AppLanguage"] = "App language",
        ["DictationLanguage"] = "Dictation language",
        ["AutoPaste"] = "Automatically paste after completion",
        ["KeepOllamaWarm"] = "Keep Ollama warm",
        ["SaveHistory"] = "Save history",
        ["Status"] = "Status",
        ["Ready"] = "Ready",
        ["AutoSaveHint"] = "Changes are saved automatically.",
        ["AutoSaving"] = "Saving automatically...",
        ["AutoSaved"] = "Automatically saved",
        ["AutoSaveFailed"] = "Automatic saving failed",
        ["RecordButtonTip"] = "Starts or stops recording. Hotkey",
        ["Provider"] = "Providers",
        ["Hotkeys"] = "Hotkeys",
        ["Prompts"] = "Prompts",
        ["Backup"] = "Backup",
        ["Version"] = "Version",
        ["CheckUpdates"] = "Check for updates",
        ["OpenDownload"] = "Open download",
        ["UpdateNotChecked"] = "Updates have not been checked yet.",
        ["CheckingUpdates"] = "Checking for updates...",
        ["AppIsCurrent"] = "BlitzText is up to date ({0}).",
        ["UpdateAvailable"] = "Update available: version {0}.",
        ["UpdateCheckFailed"] = "Update check failed: {0}",
        ["Results"] = "Result",
        ["OpenAiKeyHint"] = "The API key is stored in Windows Credential Manager.",
        ["TranscriptionModel"] = "Transcription model",
        ["RewriteModel"] = "Rewrite model",
        ["OpenRouterHint"] = "Optional rewrite provider through OpenRouter.",
        ["AnthropicHint"] = "Optional rewrite provider for Claude models.",
        ["LocalTranscription"] = "Local transcription",
        ["LocalTranscriptionHint"] = "Optional: whisper.cpp executable and a local Whisper model.",
        ["WhisperModel"] = "Whisper model",
        ["FoundWhisperModels"] = "Found models",
        ["WhisperTimeout"] = "Timeout seconds",
        ["TestWhisper"] = "Test Whisper",
        ["Browse"] = "...",
        ["OllamaHint"] = "Local or network Ollama server for rewriting.",
        ["TestOllama"] = "Test Ollama",
        ["Detect"] = "Detect",
        ["HotkeysActive"] = "Workflow hotkeys active.",
        ["RestoreDefaultHotkeys"] = "Restore default hotkeys",
        ["CustomNames"] = "Custom names",
        ["CustomNamesHint"] = "One name or term per line. These spellings are passed along as context.",
        ["TranscriptionHint"] = "Transcription hint",
        ["TranscriptionHintHelp"] = "Optional hint for speech-to-text, such as language, terms, or spelling.",
        ["WorkflowPrompts"] = "Workflow prompts",
        ["WorkflowPromptsHint"] = "These extra instructions are sent to OpenAI or Ollama during rewriting.",
        ["PromptPresets"] = "Prompt presets (Improve)",
        ["PromptPresetsHint"] = "These presets set the prompt for the Improve workflow.",
        ["Apply"] = "Apply",
        ["Improve"] = "Improve",
        ["Calm"] = "Calm down",
        ["Emojis"] = "Add emojis",
        ["TranscribeOnly"] = "Transcribe only",
        ["ResetPrompts"] = "Reset prompts",
        ["ExportSettings"] = "Export settings",
        ["ExportSettingsHint"] = "Saves providers, hotkeys, prompts, and workflow selection as JSON. API keys are not exported.",
        ["Export"] = "Export",
        ["ImportSettings"] = "Import settings",
        ["ImportSettingsHint"] = "Applies a previously exported JSON file. Existing API keys stay local.",
        ["Import"] = "Import",
        ["Copy"] = "Copy",
        ["Paste"] = "Paste",
        ["Delete"] = "Delete",
        ["SearchHistory"] = "Search history...",
        ["SearchHistoryLabel"] = "Search history",
        ["ClearHistory"] = "Clear history",
        ["Footer"] = "Press the hotkey, speak, press it again. The result lands in the clipboard or directly in the target window.",
        ["StartRecording"] = "Start recording",
        ["StopRecording"] = "Stop recording",
        ["Cancel"] = "Cancel"
    };

    public static string T(AppLanguage language, string key)
    {
        var dictionary = language == AppLanguage.English ? English : German;
        return dictionary.TryGetValue(key, out var value) ? value : key;
    }
}
