# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: EinsVier.BlitzText
PackageVersion: 0.4.1
InstallerType: wix
Scope: user
UpgradeBehavior: install
ReleaseDate: 2026-06-17
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /passive
  InstallLocation: APPFOLDER="<INSTALLPATH>"
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
    MinimumVersion: 8.0.0
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/EinsVier/blitztext-windows/releases/download/v0.4.1/BlitzText-Windows-0.4.1-win-x64.msi
  InstallerSha256: C2B90547CBD456619CD83634819A09754928DE6D64ADE9C47D1B9806AE3E30A9
  ProductCode: '{EA2547B5-CE2C-42F0-A19B-34809AA152D6}'
  AppsAndFeaturesEntries:
  - DisplayName: BlitzText Windows
    Publisher: EinsVier
    ProductCode: '{EA2547B5-CE2C-42F0-A19B-34809AA152D6}'
ManifestType: installer
ManifestVersion: 1.10.0
