# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: EinsVier.BlitzText
PackageVersion: 0.4.1
InstallerType: wix
Scope: user
UpgradeBehavior: install
ReleaseDate: 2026-06-17
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /passive
  InstallLocation: APPFOLDER="<INSTALLPATH>"
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
    MinimumVersion: 8.0.0
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/EinsVier/blitztext-windows/releases/download/v0.4.1/BlitzText-Windows-0.4.1-win-x64.msi
  InstallerSha256: D29ECC8DD158993A763EFCA618612E0EE9BDB21ECA9FAA6DC14C5B181EFE8EBC
  ProductCode: '{38B26DB8-4C2B-4EAB-A0E0-1C69A4E4AE09}'
  AppsAndFeaturesEntries:
  - DisplayName: BlitzText Windows
    Publisher: EinsVier
    ProductCode: '{38B26DB8-4C2B-4EAB-A0E0-1C69A4E4AE09}'
ManifestType: installer
ManifestVersion: 1.10.0
